#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: lts-16.31

#nix:
#  enable: true
