#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: lts-23.1

#nix:
#  enable: true

#extra-deps:
#  - vector-0.13.0.0
